### PR TITLE
new web content and alt tag configuration

### PR DESCRIPTION
**Pull request by mongmedia**

### CODE REVIEW

**Comment by duhaime** [comment]
@mongmedia This looks good! Just one question -- would it be possible to move the contact us link to `_config.yml`? That way we can keep track of everywhere this url appears, and if it needs to change we only need to change it in the main config file. There are several other google doc urls in there for reference...

**Comment by duhaime** [comment]
@mongmedia Did you push these changes in another branch? If yes, can this PR be closed and the branch deleted?

**Comment by mongmedia** [comment]
Let's close this and if there is anything missing I can updated it in a new branch

**Comment by duhaime** [comment]
@mongmedia Sounds good!

**Pull request closed without merging**
